### PR TITLE
fix: use default values in prefs/store system

### LINKED ISSUE #244: fix: the prefs/store system
The prefs/store system does not currently make use of the default values. We need to fix it so that it sets prefs to their default values in localStorage if they haven't been set yet.

### PR DESCRIPTION
**Pull request by rjfc**
Closes #244.

### CODE REVIEW

File: src/content/lib/prefs.js [hunk 1]
```diff
@@ -1,13 +1,23 @@
...
+  // Disable the user cache for bug views
+  disable_cache: false,
+};
 
 class Store {
-  get(key) {
-    return localStorage.getItem(key);
+  get(key, defaultValue) {
+    if (localStorage.getItem(key) === null && key in prefDefaults) {
+      this.set(key, defaultValue);
```
Comment (aminomancer) [inline src/content/lib/prefs.js:14]: see my comment in the issue, the get method should not have any side effects

File: src/content/lib/prefs.js [hunk 2]
```diff
@@ -1,13 +1,23 @@
...
+    }
+    return JSON.parse(localStorage.getItem(key));
```
Comment (aminomancer) [inline src/content/lib/prefs.js:16]: btw not sure why we need JSON here. all the prefs are already valid JSON types

Comment (rjfc) [reply src/content/lib/prefs.js:16]: localStorage stores values as strings. For `offline_debug` and `disable_cache`, we want a boolean `false`, not a string `"false"` (which happens without this JSON.parse)

Comment (aminomancer) [reply src/content/lib/prefs.js:16]: Makes sense, we just don't need JSON.stringify

Comment (aminomancer) [reply src/content/lib/prefs.js:16]: well I guess if user plugs in `"true"` to bugzilla_email it could bork something, so go ahead and keep it

**Review by aminomancer — APPROVED** [review]
Lgtm thanks!
